# Generated by Django 4.2.30 on 2026-05-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=150)),
                ('song_title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('shoot_date', models.DateTimeField(blank=True, null=True)),
                ('shoot_days', models.IntegerField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('pre-production', 'Pre-Production'), ('production', 'Production'), ('post-production', 'Post-Production'), ('completed', 'Completed')], max_length=50)),
                ('payment_status', models.CharField(choices=[('no-payment', 'No Payment'), ('down-payment', 'Down Payment'), ('half-paid', 'Half Paid'), ('fully-paid', 'Fully Paid')], max_length=50)),
                ('deliverables_status', models.CharField(choices=[('planning-stage', 'Planning Stage'), ('content-shot', 'Content Shot'), ('editing-stage', 'Editing Stage'), ('promotional-content-delivered', 'Promotional Content Delivered'), ('accessory-content-delivered', 'Accessory Content Delivered'), ('all-content-delivered', 'All Content Delivered')], max_length=100)),
                ('requires_social_content', models.BooleanField(default=False)),
                ('requires_cover_art', models.BooleanField(default=False)),
                ('requires_photography', models.BooleanField(default=False)),
            ],
        ),
    ]
