# Generated by Django 4.2.30 on 2026-05-06 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deliverables_status',
            field=models.CharField(choices=[('planning-stage', 'Planning Stage'), ('content-shot', 'Content Shot'), ('editing-stage', 'Editing Stage'), ('promotional-content-delivered', 'Promotional Content Delivered'), ('accessory-content-delivered', 'Accessory Content Delivered'), ('all-content-delivered', 'All Content Delivered')], default='planning-stage', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('no-payment', 'No Payment'), ('down-payment', 'Down Payment'), ('half-paid', 'Half Paid'), ('fully-paid', 'Fully Paid')], default='no-payment', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('pre-production', 'Pre-Production'), ('production', 'Production'), ('post-production', 'Post-Production'), ('completed', 'Completed')], default='pre-production', max_length=50),
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('mood', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.project')),
            ],
        ),
    ]
