# Generated by Django 4.2.30 on 2026-05-06 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_project_deliverables_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='title',
            new_name='Scene_title',
        ),
    ]
