# Generated by Django 4.2.30 on 2026-05-06 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_title_scene_scene_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scene',
            old_name='Scene_title',
            new_name='scene_title',
        ),
    ]
