# Generated by Django 4.2.30 on 2026-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_scene_title_scene_scene_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shoot_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
