# Generated by Django 4.2.30 on 2026-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_project_shoot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_type', models.CharField(blank=True, choices=[('35mm', '35mm'), ('50mm', '50mm'), ('12mm', '12mm'), ('85mm', '85mm')])),
                ('light_type', models.CharField(blank=True, choices=[('spotlight', 'Spotlight'), ('panel_lights', 'Panel Lights'), ('tube_lights', 'Tube Lights'), ('strips', 'Strips'), ('pocket_lights', 'Pocket Lights')])),
                ('tripod_style', models.CharField(blank=True, choices=[('mini', 'Mini'), ('tabletop', 'Tabletop'), ('full_size', 'Full Size')])),
                ('gimbal', models.BooleanField(default=False)),
                ('dolly', models.BooleanField(default=False)),
                ('reflectors', models.BooleanField(default=False)),
                ('green_screen', models.BooleanField(default=False)),
                ('backdrop', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('grey', 'Grey'), ('custom_color', 'Custom Color')])),
                ('props', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['scene_title']},
        ),
    ]
