# Generated by Django 4.2.30 on 2026-05-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_equipment_alter_scene_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='props',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='dolly',
            new_name='rental_required',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='backdrop',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='gimbal',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='green_screen',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='lens_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='light_type',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='reflectors',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='tripod_style',
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(blank=True, choices=[('camera', 'Camera'), ('lighting', 'Lighting'), ('set_design', 'Set Design'), ('props', 'Props'), ('camera_accessory', 'Camera Accessory'), ('audio', 'Audio'), ('stabilization', 'Stabilization'), ('backdrop', 'Backdrop'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipment',
            name='owned',
            field=models.BooleanField(default=True),
        ),
    ]
