# Generated by Django 4.2.30 on 2026-05-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_props_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='equipmenet',
            field=models.ManyToManyField(to='main_app.equipment'),
        ),
    ]
