# Generated by Django 4.2.30 on 2026-05-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_project_equipmenet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='equipmenet',
            new_name='equipment',
        ),
    ]
