# Generated by Django 4.2.30 on 2026-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_equipment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='project_cover_art/'),
        ),
    ]
